In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(f"Numpy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

Numpy version: 2.4.4
Pandas version: 3.0.2

## Creating a raw_data_set variable for data wrangler

In [62]:
raw_data_set = pd.read_csv("../data/raw/Telco-Customer-Churn.csv")
raw_data_set

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

## Checking dimensions, data types and other important details of the data set

In [63]:
print(f"Rows: {raw_data_set.shape[0]} \nColumns: {raw_data_set.shape[1]}]\n")
print(f"Data Types of columns:\n{'-'*len('Data Types of columns:')}\n{raw_data_set.dtypes}\n")

Rows: 7043
Columns: 21]

Data Types of columns:
----------------------
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

## Dropping unnecessary columns

In [64]:
raw_data_set.drop(columns=['customerID'])

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [65]:
print(list(raw_data_set.columns))
print(raw_data_set[yes_no_cols].dtypes)
print(raw_data_set[yes_no_cols].isnull().sum())

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']
Partner             str
Dependents          str
PhoneService        str
PaperlessBilling    str
Churn               str
dtype: object
Partner             0
Dependents          0
PhoneService        0
PaperlessBilling    0
Churn               0
dtype: int64

## Mapping yes/no to 1/0

In [67]:
yes_no_cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']

raw_data_set[yes_no_cols] = raw_data_set[yes_no_cols].apply(lambda x: x.map({
    "Yes": 1,
    "No": 0
}))

raw_data_set

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,NaN,NaN,1,NaN,No phone service,DSL,No,...,No,No,No,No,Month-to-month,NaN,Electronic check,29.85,29.85,NaN
1,5575-GNVDE,Male,0,NaN,NaN,34,NaN,No,DSL,Yes,...,Yes,No,No,No,One year,NaN,Mailed check,56.95,1889.5,NaN
2,3668-QPYBK,Male,0,NaN,NaN,2,NaN,No,DSL,Yes,...,No,No,No,No,Month-to-month,NaN,Mailed check,53.85,108.15,NaN
3,7795-CFOCW,Male,0,NaN,NaN,45,NaN,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,NaN,Bank transfer (automatic),42.30,1840.75,NaN
4,9237-HQITU,Female,0,NaN,NaN,2,NaN,No,Fiber optic,No,...,No,No,No,No,Month-to-month,NaN,Electronic check,70.70,151.65,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,NaN,NaN,24,NaN,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,NaN,Mailed check,84.80,1990.5,NaN
7039,2234-XADUH,Female,0,NaN,NaN,72,NaN,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,NaN,Credit card (automatic),103.20,7362.9,NaN
7040,4801-JZAZL,Female,0,NaN,NaN,11,NaN,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,NaN,Electronic check,29.60,346.45,NaN
7041,8361-LTMKD,Male,1,NaN,NaN,4,NaN,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,NaN,Mailed check,74.40,306.6,NaN
7042,3186-AJIEK,Male,0,NaN,NaN,66,NaN,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,NaN,Bank transfer (automatic),105.65,6844.5,NaN

## Mapping gender male/female to 1/0

In [68]:
raw_data_set['gender'] = raw_data_set['gender'].map({
    'Male': 1,
    'Female': 0
})

raw_data_set

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,NaN,NaN,1,NaN,No phone service,DSL,No,...,No,No,No,No,Month-to-month,NaN,Electronic check,29.85,29.85,NaN
1,5575-GNVDE,1,0,NaN,NaN,34,NaN,No,DSL,Yes,...,Yes,No,No,No,One year,NaN,Mailed check,56.95,1889.5,NaN
2,3668-QPYBK,1,0,NaN,NaN,2,NaN,No,DSL,Yes,...,No,No,No,No,Month-to-month,NaN,Mailed check,53.85,108.15,NaN
3,7795-CFOCW,1,0,NaN,NaN,45,NaN,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,NaN,Bank transfer (automatic),42.30,1840.75,NaN
4,9237-HQITU,0,0,NaN,NaN,2,NaN,No,Fiber optic,No,...,No,No,No,No,Month-to-month,NaN,Electronic check,70.70,151.65,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,1,0,NaN,NaN,24,NaN,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,NaN,Mailed check,84.80,1990.5,NaN
7039,2234-XADUH,0,0,NaN,NaN,72,NaN,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,NaN,Credit card (automatic),103.20,7362.9,NaN
7040,4801-JZAZL,0,0,NaN,NaN,11,NaN,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,NaN,Electronic check,29.60,346.45,NaN
7041,8361-LTMKD,1,1,NaN,NaN,4,NaN,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,NaN,Mailed check,74.40,306.6,NaN
7042,3186-AJIEK,1,0,NaN,NaN,66,NaN,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,NaN,Bank transfer (automatic),105.65,6844.5,NaN

## One hot encode columns

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)